name: Update Codeforces Stats

on:
  workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *"

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: python scripts/update_cf.py

      - name: Commit Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add README.md

          git commit -m "Update Codeforces Stats" || exit 0

          git push
